name: Bug report
description: Report bugs with the engine here
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your bug here."
    validations:
      required: true

  - type: textarea
    id: terminal
    attributes:
      label: "Command Prompt/Terminal logs (if existing)"
      render: bash
    validations:
      required: false

  - type: dropdown
    id: modding
    attributes:
      label: "Are you modding a build from source or with Lua?"
      options:
        - Lua
        - Source
    validations:
      required: true

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your build target?"
      options:
        - "Windows"
        - "Linux"
        - "Mac"
        - "HTML5"
        - "Flash/Air-based target"
        - "Neko, HashLink, or other build system"
    validations:
      required: true

  - type: input
    id: buildsummary
    attributes:
      label: "Did you edit anything in this build? If so, mention or summarize your changes."
      placeholder: "Yes, I edited ClientPrefs.hx and tried to add a new setting"
    validations:
      required: true
