name: Bag Prijava
description: Opišite Ovde Grešku Za SBEngine Ovde
labels: [Bag]
body:
  - type: textarea
    id: Descripcija
    attributes:
      label: "Opišite Svoju Grešku Ovde."
    validations:
      required: true

  - type: textarea
    id: terminal
    attributes:
      label: "Command Prompt/Terminal logs (Ako Postoji)"
      render: bash
    validations:
      required: false

  - type: dropdown
    id: modding
    attributes:
      label: "Da Li Modifikujete Gradnju Iz Izvora Ili Sa Lua-om?"
      options:
        - Lua
        - Izvor
    validations:
      required: true

  - type: dropdown
    id: btarget
    attributes:
      label: "Koji Je Vaš Cilj Izgradnje"
      options:
        - "Windows"
        - "Linux"
        - "Mac"
        - "Android"
    validations:
      required: true

  - type: input
    id: buildsummary
    attributes:
      label: "Da Li Ste Nešto Izmenili U Ovoj Verziji? Ako Jeste, Spomenite Lli Sumirajte Svoje Promene"
      placeholder: "Da, Izmenio Sam ClientPrefs.hx I Pokušao Da Dodam Novo Podešavanje"
    validations:
      required: true
