name: Feature Request
description: No, i won't add 6K/etc to the engine or winning icons, stop asking for it. REQUESTING FOR A STAGE EDITOR WILL RESULT IN A BAN, I ALREADY SAID I WILL DO IT LATER GOD DAMN IT.
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the base engine?
    validations:
      required: true
