name: Nepostojaća Dokumentacija
description: Tražite Dokumentaciju Ako Nešto Nedostaje.
labels: [Dokumentacija]
body:
  - type: textarea
    attributes:
      label: Šta Treba Dokumentovati?
      description: 'Na Primer: „Ne Postoji Dtranica Koja Objašnjava Kako Da Napravite Dostignuće!'
    validations:
      required: true
